apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bgpconfigurations.crd.projectcalico.org
spec:
  group: crd.projectcalico.org
  names:
    kind: BGPConfiguration
    listKind: BGPConfigurationList
    plural: bgpconfigurations
    singular: bgpconfiguration
  preserveUnknownFields: false
  scope: Cluster
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                asNumber:
                  format: int32
                  type: integer
                bindMode:
                  type: string
                communities:
                  items:
                    properties:
                      name:
                        type: string
                      value:
                        pattern: ^(\d+):(\d+)$|^(\d+):(\d+):(\d+)$
                        type: string
                    type: object
                  type: array
                ignoredInterfaces:
                  items:
                    type: string
                  type: array
                listenPort:
                  maximum: 65535
                  minimum: 1
                  type: integer
                logSeverityScreen:
                  type: string
                nodeMeshMaxRestartTime:
                  type: string
                nodeMeshPassword:
                  properties:
                    secretKeyRef:
                      properties:
                        key:
                          type: string
                        name:
                          type: string
                        optional:
                          type: boolean
                      required:
                        - key
                      type: object
                  type: object
                nodeToNodeMeshEnabled:
                  type: boolean
                prefixAdvertisements:
                  items:
                    properties:
                      cidr:
                        type: string
                      communities:
                        items:
                          type: string
                        type: array
                    type: object
                  type: array
                serviceClusterIPs:
                  items:
                    properties:
                      cidr:
                        type: string
                    type: object
                  type: array
                serviceExternalIPs:
                  items:
                    properties:
                      cidr:
                        type: string
                    type: object
                  type: array
                serviceLoadBalancerIPs:
                  items:
                    properties:
                      cidr:
                        type: string
                    type: object
                  type: array
              type: object
          type: object
      served: true
      storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
